# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_deudas_diag.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deudas_diag(object):
    def setupUi(self, deudas_diag):
        deudas_diag.setObjectName("deudas_diag")
        deudas_diag.resize(500, 555)
        deudas_diag.setMaximumSize(QtCore.QSize(500, 555))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(deudas_diag)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(deudas_diag)
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"background-color: rgb(0, 145, 217);\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 12pt;\n"
"font: 87 12pts \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(0, 0, 0);\n"
"border: 0px solid #14C80C; \n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"\n"
"border: 0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"\n"
"}\n"
"\n"
"QTextEdit{\n"
"\n"
"border: 0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(61, 61, 61);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 206, 151);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.nombre_edit = QtWidgets.QLineEdit(self.frame)
        self.nombre_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.nombre_edit.setObjectName("nombre_edit")
        self.horizontalLayout.addWidget(self.nombre_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.monto_edit = QtWidgets.QLineEdit(self.frame)
        self.monto_edit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.monto_edit.setObjectName("monto_edit")
        self.horizontalLayout_5.addWidget(self.monto_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.recibo_calendar = QtWidgets.QCalendarWidget(self.frame)
        self.recibo_calendar.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.recibo_calendar.setObjectName("recibo_calendar")
        self.horizontalLayout_6.addWidget(self.recibo_calendar)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.cobro_calendar = QtWidgets.QCalendarWidget(self.frame)
        self.cobro_calendar.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.cobro_calendar.setObjectName("cobro_calendar")
        self.horizontalLayout_8.addWidget(self.cobro_calendar)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cancel_btn = QtWidgets.QPushButton(self.frame)
        self.cancel_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_9.addWidget(self.cancel_btn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.add_btn = QtWidgets.QPushButton(self.frame)
        self.add_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_9.addWidget(self.add_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addWidget(self.frame)

        self.retranslateUi(deudas_diag)
        QtCore.QMetaObject.connectSlotsByName(deudas_diag)

    def retranslateUi(self, deudas_diag):
        _translate = QtCore.QCoreApplication.translate
        deudas_diag.setWindowTitle(_translate("deudas_diag", "Deudas"))
        self.label.setText(_translate("deudas_diag", "AÑADIR DEUDA"))
        self.label_2.setText(_translate("deudas_diag", "NOMBRE"))
        self.label_5.setText(_translate("deudas_diag", "MONTO"))
        self.label_6.setText(_translate("deudas_diag", "DIA DE RECIBO"))
        self.label_7.setText(_translate("deudas_diag", "DIA DE COBRO"))
        self.cancel_btn.setText(_translate("deudas_diag", "CANCELAR"))
        self.add_btn.setText(_translate("deudas_diag", "AÑADIR"))
