# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agregar_prod.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_agregar_prod(object):
    def setupUi(self, agregar_prod):
        agregar_prod.setObjectName("agregar_prod")
        agregar_prod.resize(500, 550)
        agregar_prod.setMinimumSize(QtCore.QSize(500, 550))
        self.horizontalLayout = QtWidgets.QHBoxLayout(agregar_prod)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(agregar_prod)
        self.frame.setStyleSheet("\n"
"\n"
"QFrame{\n"
"\n"
"background-color: rgb(0, 145, 217);\n"
"\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 12pt;\n"
"font: 87 12pts \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(0, 0, 0);\n"
"border: 0px solid #14C80C; \n"
"\n"
"}\n"
"\n"
"QLineedit{\n"
"\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"\n"
"}\n"
"\n"
"QTextEdit{\n"
"\n"
"border: 0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(61, 61, 61);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 206, 151);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_name_insert_2 = QtWidgets.QLabel(self.frame)
        self.label_name_insert_2.setObjectName("label_name_insert_2")
        self.horizontalLayout_4.addWidget(self.label_name_insert_2)
        self.line_edit_nombre = QtWidgets.QLineEdit(self.frame)
        self.line_edit_nombre.setObjectName("line_edit_nombre")
        self.horizontalLayout_4.addWidget(self.line_edit_nombre)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_desc_insert_2 = QtWidgets.QLabel(self.frame)
        self.label_desc_insert_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_desc_insert_2.setObjectName("label_desc_insert_2")
        self.horizontalLayout_5.addWidget(self.label_desc_insert_2)
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_5.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_cant_insert_2 = QtWidgets.QLabel(self.frame)
        self.label_cant_insert_2.setObjectName("label_cant_insert_2")
        self.horizontalLayout_8.addWidget(self.label_cant_insert_2)
        self.spin_edit_cant = QtWidgets.QSpinBox(self.frame)
        self.spin_edit_cant.setObjectName("spin_edit_cant")
        self.horizontalLayout_8.addWidget(self.spin_edit_cant)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_marca_insert_2 = QtWidgets.QLabel(self.frame)
        self.label_marca_insert_2.setObjectName("label_marca_insert_2")
        self.horizontalLayout_6.addWidget(self.label_marca_insert_2)
        self.line_edit_marca = QtWidgets.QLineEdit(self.frame)
        self.line_edit_marca.setObjectName("line_edit_marca")
        self.horizontalLayout_6.addWidget(self.line_edit_marca)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_modelo_insert_2 = QtWidgets.QLabel(self.frame)
        self.label_modelo_insert_2.setObjectName("label_modelo_insert_2")
        self.horizontalLayout_7.addWidget(self.label_modelo_insert_2)
        self.line_edit_modelo = QtWidgets.QLineEdit(self.frame)
        self.line_edit_modelo.setObjectName("line_edit_modelo")
        self.horizontalLayout_7.addWidget(self.line_edit_modelo)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_precio_insert_2 = QtWidgets.QLabel(self.frame)
        self.label_precio_insert_2.setObjectName("label_precio_insert_2")
        self.horizontalLayout_9.addWidget(self.label_precio_insert_2)
        self.line_edit_precio = QtWidgets.QLineEdit(self.frame)
        self.line_edit_precio.setObjectName("line_edit_precio")
        self.horizontalLayout_9.addWidget(self.line_edit_precio)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exit_btn = QtWidgets.QPushButton(self.frame)
        self.exit_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.exit_btn.setStyleSheet("\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout_3.addWidget(self.exit_btn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.done_btn = QtWidgets.QPushButton(self.frame)
        self.done_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.done_btn.setObjectName("done_btn")
        self.horizontalLayout_3.addWidget(self.done_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(agregar_prod)
        QtCore.QMetaObject.connectSlotsByName(agregar_prod)

    def retranslateUi(self, agregar_prod):
        _translate = QtCore.QCoreApplication.translate
        agregar_prod.setWindowTitle(_translate("agregar_prod", "AGREGAR PRODUCTO"))
        self.label.setText(_translate("agregar_prod", "INGRESAR PRODUCTO"))
        self.label_name_insert_2.setText(_translate("agregar_prod", "NOMBRE"))
        self.label_desc_insert_2.setText(_translate("agregar_prod", "DESCRIPCION"))
        self.label_cant_insert_2.setText(_translate("agregar_prod", "CANTIDAD"))
        self.label_marca_insert_2.setText(_translate("agregar_prod", "MARCA"))
        self.label_modelo_insert_2.setText(_translate("agregar_prod", "MODELO"))
        self.label_precio_insert_2.setText(_translate("agregar_prod", "PRECIO UNITARIO"))
        self.exit_btn.setText(_translate("agregar_prod", "SALIR"))
        self.done_btn.setText(_translate("agregar_prod", "ACEPTAR"))
