# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_user(object):
    def setupUi(self, register_user):
        register_user.setObjectName("register_user")
        register_user.resize(330, 380)
        register_user.setMinimumSize(QtCore.QSize(330, 380))
        register_user.setMaximumSize(QtCore.QSize(330, 380))
        self.verticalLayout = QtWidgets.QVBoxLayout(register_user)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(register_user)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 145, 217);\n"
"}\n"
"QLabel{\n"
"font-size: 12pt;\n"
"font: 87 12pts \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(0, 0, 0);\n"
"border: 0px solid #14C80C; \n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"\n"
"border: 0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(61, 61, 61);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 206, 151);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.user_line = QtWidgets.QLineEdit(self.frame)
        self.user_line.setMinimumSize(QtCore.QSize(0, 0))
        self.user_line.setMaximumSize(QtCore.QSize(175, 16777215))
        self.user_line.setObjectName("user_line")
        self.horizontalLayout.addWidget(self.user_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pass_line = QtWidgets.QLineEdit(self.frame)
        self.pass_line.setMaximumSize(QtCore.QSize(175, 16777215))
        self.pass_line.setObjectName("pass_line")
        self.horizontalLayout_2.addWidget(self.pass_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.close_btn = QtWidgets.QPushButton(self.frame)
        self.close_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.close_btn.setStyleSheet("QPushButton:hover{\n"
"background-color: ;\n"
"    background-color: rgb(255, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}")
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.enter_btn = QtWidgets.QPushButton(self.frame)
        self.enter_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.enter_btn.setObjectName("enter_btn")
        self.horizontalLayout_3.addWidget(self.enter_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(register_user)
        QtCore.QMetaObject.connectSlotsByName(register_user)

    def retranslateUi(self, register_user):
        _translate = QtCore.QCoreApplication.translate
        register_user.setWindowTitle(_translate("register_user", "Ingresar"))
        self.label.setText(_translate("register_user", "INGRESE DATOS DE USUARIO"))
        self.label_2.setText(_translate("register_user", "USUARIO"))
        self.label_3.setText(_translate("register_user", "CONTRASEÑA"))
        self.close_btn.setText(_translate("register_user", "CERRAR"))
        self.enter_btn.setText(_translate("register_user", "ACEPTAR"))
