# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'invUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventanaprincipal(object):
    def setupUi(self, Ventanaprincipal):
        Ventanaprincipal.setObjectName("Ventanaprincipal")
        Ventanaprincipal.resize(1116, 622)
        Ventanaprincipal.setMinimumSize(QtCore.QSize(880, 622))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icons/maxwell2.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ventanaprincipal.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Ventanaprincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("\n"
"\n"
"\n"
"background-color: rgb(0, 145, 217);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_sup = QtWidgets.QFrame(self.frame)
        self.frame_sup.setStyleSheet("\n"
"QLineEdit{\n"
"\n"
"border: 0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"\n"
"}")
        self.frame_sup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sup.setObjectName("frame_sup")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_sup)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.btn_menu = QtWidgets.QPushButton(self.frame_sup)
        self.btn_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_menu.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../recursos/img/icons/menu2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon1)
        self.btn_menu.setIconSize(QtCore.QSize(38, 38))
        self.btn_menu.setAutoRepeat(False)
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_32.addWidget(self.btn_menu)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_sup)
        self.label_2.setStyleSheet("QLabel{\n"
"font-size: 12pt;\n"
"font: 87 12pts \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(0, 0, 0);\n"
"border: 0px solid #14C80C; \n"
"\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_30.addWidget(self.label_2)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_30)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.frame_sup)
        self.label_10.setStyleSheet("QLabel{\n"
"font-size: 12pt;\n"
"font: 87 12pts \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(0, 0, 0);\n"
"border: 0px solid #14C80C; \n"
"\n"
"}\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tasa_edit = QtWidgets.QLineEdit(self.frame_sup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tasa_edit.sizePolicy().hasHeightForWidth())
        self.tasa_edit.setSizePolicy(sizePolicy)
        self.tasa_edit.setMinimumSize(QtCore.QSize(100, 0))
        self.tasa_edit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tasa_edit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tasa_edit.setAutoFillBackground(False)
        self.tasa_edit.setText("")
        self.tasa_edit.setMaxLength(5)
        self.tasa_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tasa_edit.setObjectName("tasa_edit")
        self.horizontalLayout.addWidget(self.tasa_edit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.horizontalLayout_31.addLayout(self.verticalLayout_13)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_31)
        self.verticalLayout_2.addWidget(self.frame_sup)
        self.frame_cont = QtWidgets.QFrame(self.frame)
        self.frame_cont.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cont.setObjectName("frame_cont")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_cont)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_controls = QtWidgets.QFrame(self.frame_cont)
        self.frame_controls.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_controls.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_controls.setStyleSheet("QFrame{\n"
" background-color: rgb(0, 206, 151); \n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(61, 61, 61); \n"
"border-bottom-right-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white; \n"
"border-top left-radius: 20px;\n"
" border-bottom-left-radius: 20px; \n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}")
        self.frame_controls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_controls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_controls.setObjectName("frame_controls")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_controls)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.inicio_btn = QtWidgets.QPushButton(self.frame_controls)
        self.inicio_btn.setMinimumSize(QtCore.QSize(0, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../recursos/img/icons/inicio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inicio_btn.setIcon(icon2)
        self.inicio_btn.setObjectName("inicio_btn")
        self.verticalLayout_5.addWidget(self.inicio_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.Productos_btn = QtWidgets.QPushButton(self.frame_controls)
        self.Productos_btn.setMinimumSize(QtCore.QSize(0, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../recursos/img/icons/caja.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Productos_btn.setIcon(icon3)
        self.Productos_btn.setObjectName("Productos_btn")
        self.verticalLayout_5.addWidget(self.Productos_btn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.ventas_btn = QtWidgets.QPushButton(self.frame_controls)
        self.ventas_btn.setMinimumSize(QtCore.QSize(0, 40))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../recursos/img/icons/venta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ventas_btn.setIcon(icon4)
        self.ventas_btn.setObjectName("ventas_btn")
        self.verticalLayout_5.addWidget(self.ventas_btn)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.reparacion_btn = QtWidgets.QPushButton(self.frame_controls)
        self.reparacion_btn.setMinimumSize(QtCore.QSize(0, 40))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../recursos/img/icons/libro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reparacion_btn.setIcon(icon5)
        self.reparacion_btn.setObjectName("reparacion_btn")
        self.verticalLayout_5.addWidget(self.reparacion_btn)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.ayuda_btn = QtWidgets.QPushButton(self.frame_controls)
        self.ayuda_btn.setMinimumSize(QtCore.QSize(0, 40))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../recursos/img/icons/soporte.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ayuda_btn.setIcon(icon6)
        self.ayuda_btn.setObjectName("ayuda_btn")
        self.verticalLayout_5.addWidget(self.ayuda_btn)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addWidget(self.frame_controls)
        self.frame_pag = QtWidgets.QFrame(self.frame_cont)
        self.frame_pag.setStyleSheet("QFrame{\n"
"\n"
"background-color: rgb(61, 61, 61);\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 12pt;\n"
"font: 87 12pts \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(0, 0, 0);\n"
"border: 0px solid #14C80C; \n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"\n"
"border: 0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"\n"
"}\n"
"\n"
"QTextEdit{\n"
"\n"
"border: 0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(61, 61, 61);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 206, 151);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"\n"
"\n"
"QTableWidget{\n"
"    background-color: rgb(198, 198, 198);\n"
"\n"
"font-size: 12pt;\n"
"color: #000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"\n"
"background-color: rgb(0, 206, 151);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"font-size:12pt;\n"
"\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section{\n"
"\n"
"background-color: rgb(0, 0, 0);\n"
"border:1px solid rgb(0, 206, 151);\n"
"}\n"
"\n"
"QDateEdit {\n"
"                background-color: white;\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 2px;\n"
"            }\n"
"            QDateEdit::drop-down {\n"
"                width: 20px;\n"
"\n"
"    }\n"
"\n"
"            QScrollBar:vertical {\n"
"                background-color: #333333;\n"
"                width: 10px;\n"
"                margin: 0px 0px 0px 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                background-color: #333333;\n"
"                height: 10px;\n"
"                margin: 0px 0px 0px 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background-color: #B0B0B0;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background-color: #B0B0B0;\n"
"                min-width: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::sub-line:vertical, QScrollBar::sub-line:horizontal {\n"
"                background-color: white;\n"
"                border: none;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::add-line:horizontal {\n"
"                background-color: white;\n"
"                border: none;\n"
"                border-radius: 5px;\n"
"            }\n"
"\n"
"\n"
"QComboBox{\n"
"border: 0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"          }\n"
"\n"
"\n"
"\n"
"")
        self.frame_pag.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pag.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pag.setObjectName("frame_pag")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_pag)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pag)
        self.stackedWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_inicio = QtWidgets.QWidget()
        self.page_inicio.setObjectName("page_inicio")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_inicio)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.page_inicio)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem7)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.gif_label = QtWidgets.QLabel(self.page_inicio)
        self.gif_label.setMinimumSize(QtCore.QSize(480, 270))
        self.gif_label.setMaximumSize(QtCore.QSize(480, 270))
        self.gif_label.setText("")
        self.gif_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gif_label.setObjectName("gif_label")
        self.horizontalLayout_22.addWidget(self.gif_label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.verticalLayout_11.addLayout(self.horizontalLayout_22)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.horizontalLayout_23.addLayout(self.verticalLayout_11)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_3 = QtWidgets.QLabel(self.page_inicio)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_22.addWidget(self.label_3)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem11)
        self.img_label = QtWidgets.QLabel(self.page_inicio)
        self.img_label.setMinimumSize(QtCore.QSize(0, 200))
        self.img_label.setText("")
        self.img_label.setPixmap(QtGui.QPixmap("img/icons/smart.png"))
        self.img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.img_label.setObjectName("img_label")
        self.verticalLayout_21.addWidget(self.img_label)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem12)
        self.verticalLayout_22.addLayout(self.verticalLayout_21)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.page_inicio)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_16.addWidget(self.label_7)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.hora_label = QtWidgets.QLabel(self.page_inicio)
        self.hora_label.setObjectName("hora_label")
        self.verticalLayout_15.addWidget(self.hora_label)
        self.dia_label = QtWidgets.QLabel(self.page_inicio)
        self.dia_label.setObjectName("dia_label")
        self.verticalLayout_15.addWidget(self.dia_label)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.horizontalLayout_19.addLayout(self.verticalLayout_16)
        self.verticalLayout_22.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_23.addLayout(self.verticalLayout_22)
        self.verticalLayout_23.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_28 = QtWidgets.QLabel(self.page_inicio)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_20.addWidget(self.label_28)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem13)
        self.verticalLayout_23.addLayout(self.horizontalLayout_20)
        self.stackedWidget.addWidget(self.page_inicio)
        self.page_productos = QtWidgets.QWidget()
        self.page_productos.setObjectName("page_productos")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_productos)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.page_productos)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.page_productos)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.buscar_prod_line = QtWidgets.QLineEdit(self.page_productos)
        self.buscar_prod_line.setMinimumSize(QtCore.QSize(100, 0))
        self.buscar_prod_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.buscar_prod_line.setObjectName("buscar_prod_line")
        self.horizontalLayout_13.addWidget(self.buscar_prod_line)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self.buscar_btn = QtWidgets.QPushButton(self.page_productos)
        self.buscar_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.buscar_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.buscar_btn.setObjectName("buscar_btn")
        self.horizontalLayout_13.addWidget(self.buscar_btn)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem15)
        self.save_btn = QtWidgets.QPushButton(self.page_productos)
        self.save_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.save_btn.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 127);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_13.addWidget(self.save_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.table_prod = QtWidgets.QTableWidget(self.page_productos)
        self.table_prod.setObjectName("table_prod")
        self.table_prod.setColumnCount(8)
        self.table_prod.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_prod.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_prod.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_prod.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_prod.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_prod.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_prod.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_prod.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_prod.setHorizontalHeaderItem(7, item)
        self.verticalLayout.addWidget(self.table_prod)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clear_btn = QtWidgets.QPushButton(self.page_productos)
        self.clear_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.clear_btn.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(255, 27, 6);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_3.addWidget(self.clear_btn)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.add_btn = QtWidgets.QPushButton(self.page_productos)
        self.add_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.add_btn.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: rgb(1, 255, 43);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_3.addWidget(self.add_btn)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.edit_btn = QtWidgets.QPushButton(self.page_productos)
        self.edit_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.edit_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(19, 212, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout_3.addWidget(self.edit_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.page_productos)
        self.page_ventas = QtWidgets.QWidget()
        self.page_ventas.setObjectName("page_ventas")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_ventas)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.page_ventas)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_6 = QtWidgets.QLabel(self.page_ventas)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_27.addWidget(self.label_6)
        self.prod_name_edit = QtWidgets.QLineEdit(self.page_ventas)
        self.prod_name_edit.setMinimumSize(QtCore.QSize(100, 0))
        self.prod_name_edit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.prod_name_edit.setObjectName("prod_name_edit")
        self.horizontalLayout_27.addWidget(self.prod_name_edit)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.page_ventas)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.id_prod_edit = QtWidgets.QLineEdit(self.page_ventas)
        self.id_prod_edit.setObjectName("id_prod_edit")
        self.horizontalLayout_7.addWidget(self.id_prod_edit)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem18)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.page_ventas)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.cant_prod = QtWidgets.QLineEdit(self.page_ventas)
        self.cant_prod.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cant_prod.setObjectName("cant_prod")
        self.horizontalLayout_8.addWidget(self.cant_prod)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.add_v_btn = QtWidgets.QPushButton(self.page_ventas)
        self.add_v_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.add_v_btn.setObjectName("add_v_btn")
        self.horizontalLayout_9.addWidget(self.add_v_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.page_ventas)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.table_prod_comprados = QtWidgets.QTableWidget(self.page_ventas)
        self.table_prod_comprados.setMaximumSize(QtCore.QSize(700, 750))
        self.table_prod_comprados.setObjectName("table_prod_comprados")
        self.table_prod_comprados.setColumnCount(9)
        self.table_prod_comprados.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_prod_comprados.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_prod_comprados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_prod_comprados.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_prod_comprados.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_prod_comprados.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_prod_comprados.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_prod_comprados.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_prod_comprados.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_prod_comprados.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.table_prod_comprados.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_prod_comprados.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_prod_comprados.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_prod_comprados.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_prod_comprados.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_prod_comprados.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(202, 202, 0))
        brush.setStyle(QtCore.Qt.Dense3Pattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_prod_comprados.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 102))
        brush.setStyle(QtCore.Qt.Dense3Pattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_prod_comprados.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_prod_comprados.setItem(0, 8, item)
        self.verticalLayout_4.addWidget(self.table_prod_comprados)
        self.horizontalLayout_29.addLayout(self.verticalLayout_4)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem19)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem20)
        self.save_v_btn = QtWidgets.QPushButton(self.page_ventas)
        self.save_v_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.save_v_btn.setMaximumSize(QtCore.QSize(120, 30))
        self.save_v_btn.setObjectName("save_v_btn")
        self.verticalLayout_9.addWidget(self.save_v_btn)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem21)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_29.addLayout(self.verticalLayout_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.delete_btn = QtWidgets.QPushButton(self.page_ventas)
        self.delete_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.delete_btn.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(255, 27, 6);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_21.addWidget(self.delete_btn)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem22)
        self.clear_venta_btn = QtWidgets.QPushButton(self.page_ventas)
        self.clear_venta_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.clear_venta_btn.setStyleSheet("\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.clear_venta_btn.setObjectName("clear_venta_btn")
        self.horizontalLayout_21.addWidget(self.clear_venta_btn)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem23)
        self.cierre_btn = QtWidgets.QPushButton(self.page_ventas)
        self.cierre_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.cierre_btn.setObjectName("cierre_btn")
        self.horizontalLayout_21.addWidget(self.cierre_btn)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem24)
        self.buscar_venta_btn = QtWidgets.QPushButton(self.page_ventas)
        self.buscar_venta_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.buscar_venta_btn.setObjectName("buscar_venta_btn")
        self.horizontalLayout_21.addWidget(self.buscar_venta_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.stackedWidget.addWidget(self.page_ventas)
        self.page_reparaciones = QtWidgets.QWidget()
        self.page_reparaciones.setObjectName("page_reparaciones")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_reparaciones)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_5 = QtWidgets.QLabel(self.page_reparaciones)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_20.addWidget(self.label_5)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_25 = QtWidgets.QLabel(self.page_reparaciones)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_18.addWidget(self.label_25)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.page_reparaciones)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        spacerItem25 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem25)
        self.ci_rep_line = QtWidgets.QLineEdit(self.page_reparaciones)
        self.ci_rep_line.setMinimumSize(QtCore.QSize(200, 0))
        self.ci_rep_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ci_rep_line.setObjectName("ci_rep_line")
        self.horizontalLayout_6.addWidget(self.ci_rep_line)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_6)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem26)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem27)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_24 = QtWidgets.QLabel(self.page_reparaciones)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.name_rep_line = QtWidgets.QLineEdit(self.page_reparaciones)
        self.name_rep_line.setObjectName("name_rep_line")
        self.horizontalLayout_10.addWidget(self.name_rep_line)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_10)
        self.verticalLayout_17.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_23 = QtWidgets.QLabel(self.page_reparaciones)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.tel_line = QtWidgets.QLineEdit(self.page_reparaciones)
        self.tel_line.setMinimumSize(QtCore.QSize(200, 0))
        self.tel_line.setMaximumSize(QtCore.QSize(200, 23))
        self.tel_line.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tel_line.setObjectName("tel_line")
        self.horizontalLayout_11.addWidget(self.tel_line)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_11)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem28)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem29)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem30)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.page_reparaciones)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.page_reparaciones)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_12.addWidget(self.dateEdit_2)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_12)
        self.verticalLayout_17.addLayout(self.horizontalLayout_18)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.verticalLayout_20.addLayout(self.verticalLayout_18)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem31)
        self.label_16 = QtWidgets.QLabel(self.page_reparaciones)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.desc_rep_text = QtWidgets.QTextEdit(self.page_reparaciones)
        self.desc_rep_text.setObjectName("desc_rep_text")
        self.verticalLayout_6.addWidget(self.desc_rep_text)
        self.horizontalLayout_16.addLayout(self.verticalLayout_6)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(100, -1, -1, -1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem32)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.page_reparaciones)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.horizontalLayout_14.setStretch(0, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.pago_line = QtWidgets.QLineEdit(self.page_reparaciones)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pago_line.setFont(font)
        self.pago_line.setMaxLength(32767)
        self.pago_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pago_line.setObjectName("pago_line")
        self.verticalLayout_12.addWidget(self.pago_line)
        self.verticalLayout_19.addLayout(self.verticalLayout_12)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem33)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_22 = QtWidgets.QLabel(self.page_reparaciones)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_14.addWidget(self.label_22)
        self.dolar_rep_line = QtWidgets.QLineEdit(self.page_reparaciones)
        self.dolar_rep_line.setMaxLength(32767)
        self.dolar_rep_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dolar_rep_line.setObjectName("dolar_rep_line")
        self.verticalLayout_14.addWidget(self.dolar_rep_line)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem34)
        self.verticalLayout_19.addLayout(self.verticalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_19)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.verticalLayout_20.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_reparaciones)
        self.pushButton_4.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_4.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(255, 27, 6);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem35)
        self.pushButton = QtWidgets.QPushButton(self.page_reparaciones)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem36)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_reparaciones)
        self.pushButton_5.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.verticalLayout_20.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.page_reparaciones)
        self.page_ayuda = QtWidgets.QWidget()
        self.page_ayuda.setObjectName("page_ayuda")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.page_ayuda)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem37)
        self.supp_label = QtWidgets.QLabel(self.page_ayuda)
        self.supp_label.setObjectName("supp_label")
        self.verticalLayout_25.addWidget(self.supp_label)
        self.horizontalLayout_25.addLayout(self.verticalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem38)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        spacerItem39 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem39)
        self.manual_label = QtWidgets.QLabel(self.page_ayuda)
        self.manual_label.setMinimumSize(QtCore.QSize(350, 390))
        self.manual_label.setText("")
        self.manual_label.setObjectName("manual_label")
        self.verticalLayout_24.addWidget(self.manual_label)
        self.menu_btn = QtWidgets.QPushButton(self.page_ayuda)
        self.menu_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.menu_btn.setObjectName("menu_btn")
        self.verticalLayout_24.addWidget(self.menu_btn)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem40)
        self.horizontalLayout_24.addLayout(self.verticalLayout_24)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_25)
        self.stackedWidget.addWidget(self.page_ayuda)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pag)
        self.verticalLayout_2.addWidget(self.frame_cont)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.horizontalLayout_5.addWidget(self.frame)
        Ventanaprincipal.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Ventanaprincipal)
        self.statusbar.setObjectName("statusbar")
        Ventanaprincipal.setStatusBar(self.statusbar)

        self.retranslateUi(Ventanaprincipal)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Ventanaprincipal)

    def retranslateUi(self, Ventanaprincipal):
        _translate = QtCore.QCoreApplication.translate
        Ventanaprincipal.setWindowTitle(_translate("Ventanaprincipal", "Inventario"))
        self.label_2.setText(_translate("Ventanaprincipal", "SISTEMA DE CONTROL DE INVENTARIO"))
        self.label_10.setText(_translate("Ventanaprincipal", "TASA ACTUAL"))
        self.tasa_edit.setPlaceholderText(_translate("Ventanaprincipal", "$"))
        self.inicio_btn.setText(_translate("Ventanaprincipal", "INICIO"))
        self.Productos_btn.setText(_translate("Ventanaprincipal", "PRODUCTOS"))
        self.ventas_btn.setText(_translate("Ventanaprincipal", "SALIDA"))
        self.reparacion_btn.setText(_translate("Ventanaprincipal", "REPARACIONES"))
        self.ayuda_btn.setText(_translate("Ventanaprincipal", "AYUDA"))
        self.label_17.setText(_translate("Ventanaprincipal", "SISTEMA DE CONTROL DE INVENTARIO"))
        self.label_3.setText(_translate("Ventanaprincipal", "SMART TECH STORE"))
        self.label_7.setText(_translate("Ventanaprincipal", "Bienvenido"))
        self.hora_label.setText(_translate("Ventanaprincipal", "03:02 PM"))
        self.dia_label.setText(_translate("Ventanaprincipal", "DOMINGO 17 DE MARZO DEL 2024"))
        self.label_28.setText(_translate("Ventanaprincipal", "POR FAVOR SELECCIONE UNA OPCION DEL MENU LATERAL"))
        self.label.setText(_translate("Ventanaprincipal", "PRODUCTOS"))
        self.label_19.setText(_translate("Ventanaprincipal", "NOMBRE DEL PRODUCTO"))
        self.buscar_btn.setText(_translate("Ventanaprincipal", "BUSCAR"))
        self.save_btn.setText(_translate("Ventanaprincipal", "GUARDAR"))
        item = self.table_prod.horizontalHeaderItem(0)
        item.setText(_translate("Ventanaprincipal", "ID"))
        item = self.table_prod.horizontalHeaderItem(1)
        item.setText(_translate("Ventanaprincipal", "NOMBRE"))
        item = self.table_prod.horizontalHeaderItem(2)
        item.setText(_translate("Ventanaprincipal", "MODELO"))
        item = self.table_prod.horizontalHeaderItem(3)
        item.setText(_translate("Ventanaprincipal", "MARCA"))
        item = self.table_prod.horizontalHeaderItem(4)
        item.setText(_translate("Ventanaprincipal", "CANTIDAD"))
        item = self.table_prod.horizontalHeaderItem(5)
        item.setText(_translate("Ventanaprincipal", "PRECIO UNIT"))
        item = self.table_prod.horizontalHeaderItem(6)
        item.setText(_translate("Ventanaprincipal", "PRECIO Bs"))
        item = self.table_prod.horizontalHeaderItem(7)
        item.setText(_translate("Ventanaprincipal", "PRECIO STOCK"))
        self.clear_btn.setText(_translate("Ventanaprincipal", "ELIMINAR"))
        self.add_btn.setText(_translate("Ventanaprincipal", "AGREGAR"))
        self.edit_btn.setText(_translate("Ventanaprincipal", "EDITAR"))
        self.label_8.setText(_translate("Ventanaprincipal", "VENTAS"))
        self.label_6.setText(_translate("Ventanaprincipal", "NOMBRE DEL PRODUCTO"))
        self.label_12.setText(_translate("Ventanaprincipal", "ID PROD"))
        self.label_11.setText(_translate("Ventanaprincipal", "CANTIDAD"))
        self.add_v_btn.setText(_translate("Ventanaprincipal", "AÑADIR"))
        self.label_4.setText(_translate("Ventanaprincipal", "PRODUCTOS COMPRADOS"))
        item = self.table_prod_comprados.horizontalHeaderItem(0)
        item.setText(_translate("Ventanaprincipal", "ID"))
        item = self.table_prod_comprados.horizontalHeaderItem(1)
        item.setText(_translate("Ventanaprincipal", "NOMBRE"))
        item = self.table_prod_comprados.horizontalHeaderItem(2)
        item.setText(_translate("Ventanaprincipal", "MARCA"))
        item = self.table_prod_comprados.horizontalHeaderItem(3)
        item.setText(_translate("Ventanaprincipal", "MODELO"))
        item = self.table_prod_comprados.horizontalHeaderItem(4)
        item.setText(_translate("Ventanaprincipal", "CANT"))
        item = self.table_prod_comprados.horizontalHeaderItem(5)
        item.setText(_translate("Ventanaprincipal", "PRECIO UNIT"))
        item = self.table_prod_comprados.horizontalHeaderItem(6)
        item.setText(_translate("Ventanaprincipal", "PRECIO VENTA"))
        item = self.table_prod_comprados.horizontalHeaderItem(7)
        item.setText(_translate("Ventanaprincipal", "PRECIO EN Bs"))
        __sortingEnabled = self.table_prod_comprados.isSortingEnabled()
        self.table_prod_comprados.setSortingEnabled(False)
        item = self.table_prod_comprados.item(0, 6)
        item.setText(_translate("Ventanaprincipal", "$"))
        item = self.table_prod_comprados.item(0, 7)
        item.setText(_translate("Ventanaprincipal", "Bs"))
        item = self.table_prod_comprados.item(0, 8)
        item.setText(_translate("Ventanaprincipal", "TOTAL"))
        self.table_prod_comprados.setSortingEnabled(__sortingEnabled)
        self.save_v_btn.setText(_translate("Ventanaprincipal", "GUARDAR"))
        self.delete_btn.setText(_translate("Ventanaprincipal", "DEVOLVER"))
        self.clear_venta_btn.setText(_translate("Ventanaprincipal", "LIMPIAR"))
        self.cierre_btn.setText(_translate("Ventanaprincipal", "CIERRE"))
        self.buscar_venta_btn.setText(_translate("Ventanaprincipal", "BUSCAR"))
        self.label_5.setText(_translate("Ventanaprincipal", "REPARACIONES"))
        self.label_25.setText(_translate("Ventanaprincipal", "DATOS "))
        self.label_14.setText(_translate("Ventanaprincipal", "CEDULA"))
        self.label_24.setText(_translate("Ventanaprincipal", "NOMBRE"))
        self.label_23.setText(_translate("Ventanaprincipal", "TELEFONO"))
        self.label_15.setText(_translate("Ventanaprincipal", "FECHA"))
        self.label_16.setText(_translate("Ventanaprincipal", "DESCRIPCION"))
        self.label_21.setText(_translate("Ventanaprincipal", "PAGO EN Bs"))
        self.label_22.setText(_translate("Ventanaprincipal", "PAGO EN $$$"))
        self.dolar_rep_line.setPlaceholderText(_translate("Ventanaprincipal", "$"))
        self.pushButton_4.setText(_translate("Ventanaprincipal", "ELIMINAR"))
        self.pushButton.setText(_translate("Ventanaprincipal", "LIMPIAR"))
        self.pushButton_5.setText(_translate("Ventanaprincipal", "AGREGAR"))
        self.supp_label.setText(_translate("Ventanaprincipal", "SOPORTE"))
        self.menu_btn.setText(_translate("Ventanaprincipal", "OPRIMA AQUI"))
