# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventas_diarias.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(993, 677)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"background-color: rgb(0, 145, 217);\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 12pt;\n"
"font: 87 12pts \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(0, 0, 0);\n"
"border: 0px solid #14C80C; \n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"\n"
"border: 0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"\n"
"}\n"
"\n"
"QTextEdit{\n"
"\n"
"border: 0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom:2px solid rgb(61, 61, 61);\n"
"font:75 12pt \"Times New Roman\" ;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(61, 61, 61);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 206, 151);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"\n"
"\n"
"QTableWidget{\n"
"    background-color: rgb(198, 198, 198);\n"
"gridine-color: rgb(0, 206, 151);\n"
"font-size: 12pt;\n"
"color: #000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"\n"
"background-color: rgb(0, 206, 151);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"font-size:12pt;\n"
"\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section{\n"
"\n"
"background-color: rgb(0, 0, 0);\n"
"border:1px solid rgb(0, 206, 151);\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tasa_label = QtWidgets.QLabel(self.frame)
        self.tasa_label.setText("")
        self.tasa_label.setObjectName("tasa_label")
        self.verticalLayout.addWidget(self.tasa_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.table_day_ventas = QtWidgets.QTableWidget(self.frame)
        self.table_day_ventas.setObjectName("table_day_ventas")
        self.table_day_ventas.setColumnCount(5)
        self.table_day_ventas.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_day_ventas.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_day_ventas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_day_ventas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_day_ventas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_day_ventas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_day_ventas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_day_ventas.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_day_ventas.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 0))
        brush.setStyle(QtCore.Qt.Dense3Pattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_day_ventas.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 0))
        brush.setStyle(QtCore.Qt.Dense3Pattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_day_ventas.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_day_ventas.setItem(0, 4, item)
        self.horizontalLayout_3.addWidget(self.table_day_ventas)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.exp_btn = QtWidgets.QPushButton(self.frame)
        self.exp_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.exp_btn.setObjectName("exp_btn")
        self.verticalLayout_2.addWidget(self.exp_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.close_btn = QtWidgets.QPushButton(self.frame)
        self.close_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.close_btn.setObjectName("close_btn")
        self.verticalLayout_2.addWidget(self.close_btn)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "VENTAS DE HOY"))
        self.label_2.setText(_translate("Dialog", "TASA USADA:"))
        item = self.table_day_ventas.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "CEDULA"))
        item = self.table_day_ventas.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "HORA"))
        item = self.table_day_ventas.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "MONTO Bs"))
        item = self.table_day_ventas.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "MONTO $$$"))
        __sortingEnabled = self.table_day_ventas.isSortingEnabled()
        self.table_day_ventas.setSortingEnabled(False)
        item = self.table_day_ventas.item(0, 2)
        item.setText(_translate("Dialog", "Bs"))
        item = self.table_day_ventas.item(0, 3)
        item.setText(_translate("Dialog", "$"))
        item = self.table_day_ventas.item(0, 4)
        item.setText(_translate("Dialog", "TOTAL"))
        self.table_day_ventas.setSortingEnabled(__sortingEnabled)
        self.exp_btn.setText(_translate("Dialog", "EXPORTAR"))
        self.close_btn.setText(_translate("Dialog", "SALIR"))
